### ISSUE TITLE
models.token not find 

### ISSUE THREAD

**Issue by V-yw** [qishu321/cmdb-ops-flow#1]

**Comment by qishu321** [comment]
![image](https://github.com/qishu321/cmdb-ops-flow/assets/95009146/2fdcdfd8-0c43-40fc-ae81-7f1b1beb29df)
![image](https://github.com/qishu321/cmdb-ops-flow/assets/95009146/bfb5a86f-1dc9-4b42-b466-c02a8c6cf013)
Token在这里，这只是我练手玩的，目前不会继续迭代了，谢谢你！
